name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t maliabhi23/skin-cancer-api:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push maliabhi23/skin-cancer-api:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push maliabhi23/myime:latest

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker pull maliabhi23/skin-cancer-api:latest
            docker stop skin-cancer-api || true && docker rm skin-cancer-api || true
            docker run -d -p 5000:5000 --name skin-cancer-api maliabhi23/skin-cancer-api:latest
